#!/usr/bin/with-contenv bash

CMD=$2

if [ "$CMD" = "stop" ]; then
	echo "Stopping AMP"
	s6-svc -to /var/run/s6/services/amp
	# -t send a SIGTERM to AMP
	# -o do not restart AMP when it dies
	exit 0
fi
if [ "$CMD" = "upgrade" ]; then
	echo "Updating AMP"
	s6-setuidgid abc ampinstmgr UpgradeAll
	exit 0
fi

echo "Invalid usage, use 'amp <stop/upgrade>'"
exit 1
