#!/usr/bin/with-contenv bash

redirect_cmd() {
	if [ "${DEBUG}" = "true" ]; then
		"$@"
	else
		"$@" >/dev/null 2>&1
	fi
}

_term() {
	echo "Caught SIGTERM signal!"
	redirect_cmd s6-setuidgid abc \
		ampinstmgr StopAll
}

trap _term SIGTERM

redirect_cmd s6-setuidgid abc \
	ampinstmgr StartBoot

PID=$(pgrep tmux)

while kill -0 "$PID" 2>/dev/null; do
	:
done
