#!/usr/bin/with-contenv bash

# attempt gracefull shutdown
stopamp() {
    echo "Caught SIGTERM signal!"
    s6-setuidgid abc \
        ampinstmgr StopAll
}
trap stopamp SIGTERM

s6-setuidgid abc \
    ampinstmgr StartBoot

# ampinstmgr creates another process then exits, prevents s6 restarting process
PID=$(pgrep tmux)
while kill -0 "${PID}" 2>/dev/null; do
    sleep 1
done
