#!/usr/bin/with-contenv bash

# can't yet determine installed build version, just main version

# upgrade instances
if [ -f /config/.ampdata/instances/Main/AMPVersion ]; then
    OLD=$(cat /config/.ampdata/instances/Main/AMPVersion)

    if [[ "${AMP_VERSION//./}" -gt "${OLD//./}" ]]; then
        echo "Upgrading all instances from ${OLD} to ${AMP_VERSION}"
        s6-setuidgid abc ampinstmgr UpgradeAll
    fi
fi
