#!/usr/bin/with-contenv bash

# upgrade instances
OLD=$(cat /config/.ampdata/instances/Main/AMPVersion)

if [[ "${VERSION//./}" -gt "${OLD//./}" ]]; then
	echo "Upgrading all instances from ${OLD} to ${VERSION//./}"
	s6-setuidgid abc ampinstmgr UpgradeAll
fi

# cleanup after ourselves
rm -f /config/.ampdata/instances/AMPCache-*.zip