#!/usr/bin/with-contenv bash

# find the latest cached zip
LATEST_ZIP_FILE=$(find /app/amp/ -name 'AMP-*-*.zip' | sort | tail -n 1)

# extract the build and architecture from the zip
ARCHITECTURE=$(echo "${LATEST_ZIP_FILE}" | sed 's|.*/AMP-\(.*\)-.*\.zip|\1|')
LATEST_BUILD=$(echo "${LATEST_ZIP_FILE}" | sed 's|.*/AMP-.*-\(.*\)\.zip|\1|')

# make folders
mkdir -p \
    /config/.ampdata/instances/ \
    /config/.ampdata/Versions/Mainline/${LATEST_BUILD}

# symlink cached amp to where amp expects it to be
ln -sf "${LATEST_ZIP_FILE}" "/config/.ampdata/Versions/Mainline/${LATEST_BUILD}/AMP_${ARCHITECTURE}.zip"

# change owner of /config
chown -R abc:abc /config

# create main instance if it does not exist
if [ ! -d /config/.ampdata/instances/Main ]; then
    s6-setuidgid abc ampinstmgr CreateInstance "${MODULE}" Main 0.0.0.0 8080 "${LICENCE}" "${USERNAME}" "${PASSWORD}"
    s6-setuidgid abc ampinstmgr ShowInstanceInfo Main | grep "Start on Boot" | grep "No" && s6-setuidgid abc ampinstmgr SetStartBoot Main yes || :
fi
