#!/usr/bin/with-contenv bash

# install java versions supplied in JAVA_VERSIONS variable
if [ -n "${JAVA_VERSIONS}" ]; then
    for i in ${JAVA_VERSIONS//,/ }; do
        if ! apk add --no-cache openjdk${i}-jre &>/dev/null; then
            echo "Could not install openjdk${i}-jre! Is it a supported java version?"
        else
            echo "Installed openjdk${i}-jre"
        fi
    done
else
    echo "No java versions are specified in the 'JAVA_VERSIONS' variable."
fi
