#!/usr/bin/with-contenv bash

# install java versions supplied in JAVA_VERSIONS variable
if [ -n "${JAVA_VERSIONS}" ]; then
    for i in ${JAVA_VERSIONS//,/ }; do
        if [[ "$i" =~ ^([7-9]|1[0-7])$ ]]; then
            TO_INSTALL="openjdk${i}-jre $TO_INSTALL"
        else
            echo "Can't find openjdk${i}-jre! Is it a supported java version?"
        fi
    done
    echo "Installing versions of java: $TO_INSTALL"
    apk add "$TO_INSTALL" &>/dev/null
else
    echo "No java versions are specified in the JAVA_VERSIONS variable."
fi
