#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config/.ampdata/instances/

if [ -d /config/instances ]; then
	echo "Migrating from old folder structure"
	mv /config/instances* /config/.ampdata
	sed -i \
		"s|/home/abc/|/config/|g" \
		/config/.ampdata/instances.json
fi

# copy the pre-cached AMPCache from the image
rm -f /config/.ampdata/instances/AMPCache-*.zip
ln -sf /app/amp/AMPCache-*.zip /config/.ampdata/instances/

# set permissions so amp can write to directories
chown -R abc:abc \
	/config/

# ensure a license was set
if [ -z "${LICENCE}" ]; then
	echo "Error: No licence specified. You need to have a valid AMP licence from cubecoders.com specified in the LICENCE environment variable"
	sleep infinity
fi

# create main instance if not exists
if [ ! -d /config/.ampdata/instances/Main ]; then
	echo "Creating main instance"
	s6-setuidgid abc ampinstmgr CreateInstance "${MODULE}" Main 0.0.0.0 8080 "${LICENCE}" "${USERNAME}" "${PASSWORD}"
fi

# upgrade instances
OLD=$(cat /config/.ampdata/instances/Main/AMPVersion)

if [[ "${AMP_VERSION//./}" -gt "${OLD//./}" ]]; then
	echo "Upgrading all instances from ${OLD} to ${AMP_VERSION//./}"
	s6-setuidgid abc ampinstmgr UpgradeAll
fi

# set main instance to start on boot if not already.
s6-setuidgid abc ampinstmgr ShowInstanceInfo Main | grep "Start on Boot" | grep "No" && s6-setuidgid abc ampinstmgr SetStartBoot Main || true
