#!/usr/bin/with-contenv bash

# supported JDK versions:
# https://pkgs.alpinelinux.org/packages?name=openjdk*-jre-headless&branch=edge&arch=x86_64

# update to hide errors
apk update -q

# 1. check if jdk version(s) is specified.
if [ -n "${JDK_VERSIONS}" ]; then
	for version in ${JDK_VERSIONS}; do
		# 2. check if version is allowed. between 9 and 15 is currently supported.
		if [ "$version" -ge "9" ] && [ "$version" -le "15" ]; then
			# 3. check if jdk is already installed, if so skip installation
			if [ ! "$(apk info | grep -E "openjdk$version-jre-headless" | sed 's/[^0-9]*//g')" = "$version" ]; then
				echo "Installing openjdk$version-jre-headless"
				apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing -q \
					"openjdk$version-jre-headless"
			fi # end 3.
		else
			echo "Error: openjdk$version-jre-headless is not supported. See below for supported JDK Versions"
			echo "https://pkgs.alpinelinux.org/packages?name=openjdk*-jre-headless&branch=edge&arch=x86_64"
		fi # end 2.
	done
else
	echo "Warning: No OpenJDK version(s) is specified. Skipping installation"
fi # end 1.

rm -rf /tmp
